name: CI/CD Pipeline for Time Tracker Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build the Docker image from the Dockerfile
      - name: Build Docker image
        run: |
          docker build -t time-tracker-app .

      # Step 4: Run the tests inside Docker container
      - name: Run tests inside Docker container
        run: |
          docker run --rm time-tracker-app bash -c "pip install -r requirements.txt && pytest --maxfail=1 --disable-warnings -q"

      # Step 5: Optionally, start the application (e.g., for integration testing)
      - name: Run the application in the Docker container
        run: |
          docker run -d -p 5000:5000 time-tracker-app

      # Step 6: Optionally, run integration tests against the live app
      - name: Run integration tests
        run: |
          # Example of running curl requests to test the app
          curl -f http://localhost:5000/clock_in/test_user

      # Step 7: Cleanup - Stop the running container
      - name: Stop Docker container
        run: |
          docker ps -q --filter "ancestor=time-tracker-app" | xargs docker stop || true
